#!/bin/bash
usage() { echo "Usage: $0 [-s <wiki1 or wiki2>] [-p <string>]" 1>&2; exit 1; }

echo "1st = $1"
echo "2nd = $2"

while getopts ":b:p:" o; do
    case "${o}" in
        b)
            b=${OPTARG}
            ((b == "wiki1" || b == "wiki2")) || usage
            ;;
        p)
            p=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${b}" ] || [ -z "${p}" ]; then
    usage
fi

echo "b = ${b}"
echo "p = ${p}"


